GENRE_MAPPING = {
 'alternative': ['polish alternative', 'south african alternative'],
 'classical': ['orchestral soundtrack',
               'kundalini',
               'piano',
               'choral',
               'opera',
               'symphonic',
               'soundtrack',
               'broadway',
               'orchestral',
               'symphonic power metal',
               'new americana',
               'operatic'],
 'country': ['country',
             'country pop',
             'college a cappella',
             'bluegrass',
             'classic country',
             'contemporary country',
             'shanty',
             'classic oklahoma country',
             'mariachi',
             'ambient country',
             'country rock',
             'mexican indie',
             'canadian country',
             'mississippi indie',
             'outlaw country',
             'ranchera'],
 'dance': ['club',
           'uk reggae',
           'eurodance',
           'edm',
           'house',
           'deep house',
           'electro house',
           'techno',
           'progressive house',
           'tropical house',
           'dancehall',
           'bass music',
           'trance',
           'vintage schlager',
           'disco',
           'dubstep',
           'drum and bass',
           'garage'],
 'electronic': ['pluggnb',
                'bass house',
                'basshall',
                'ambient',
                'electropop',
                'synthwave',
                'industrial',
                'german dance',
                'german house',
                'neo-singer-songwriter',
                'slowed and reverb',
                'chillwave',
                'trap queen',
                'slap house',
                'tropical house',
                'video game music',
                'gaming edm',
                'deep euro house',
                'uk dance',
                'electro',
                'disco house',
                'dark clubbing',
                'ambient folk',
                'psychedelic trance',
                'downtempo'],
 'experimental': ['musica tradicional cubana',
                  'vogue',
                  'charva',
                  'high vibe',
                  'dark clubbing',
                  'epicore',
                  'comedy rap',
                  'escape room',
                  "children's music",
                  'musical advocacy',
                  'show tunes',
                  'talent show',
                  'comedie musicale',
                  'bossbeat',
                  'experimental pop',
                  'aussietronica',
                  'middle earth'],
 'folk': ['folk-pop',
          'indie folk',
          'folk rock',
          'native american traditional',
          'stomp and holler',
          'shanty',
          'ambient folk',
          'celtic',
          'irish folk',
          'chamber folk',
          'singer-songwriter',
          'shamanic',
          'neo-singer-songwriter',
          'kleinkunst',
          'musica mexicana'],
 'grime': ['grime'],
 'hip hop': ['brooklyn drill',
             'jersey club',
             'latin hip hop',
             'r&drill',
             'melodic drill',
             'lgbtq+ hip hop',
             'chicago rap',
             'rap conscient',
             'chicago drill',
             'alt z',
             'trap latino',
             'old school hip hop',
             'gangster rap',
             'cloud rap francais',
             'trap',
             'australian hip hop',
             'chill drill',
             'uk hip hop',
             'phonk',
             'spanish hip hop',
             'miami hip hop',
             'sacramento hip hop',
             'uk alternative hip hop',
             'hip hop',
             'viral rap',
             'indie hip hop',
             'atl hip hop',
             'instrumental grime',
             'east coast hip hop',
             'trap queen',
             'boom bap',
             'polish hip hop',
             'canadian old school hip hop',
             'sad rap',
             'alabama rap',
             'alternative hip hop',
             'canadian hip hop',
             'christian hip hop',
             'peruvian hip hop',
             'atlantic canada hip hop',
             'colombian hip hop',
             'southern hip hop',
             'emo rap',
             'battle rap',
             'detroit hip hop',
             'melodic rap',
             'uk drill',
             'scouse rap',
             'belgian hip hop',
             'west coast rap',
             'french hip hop',
             'rage rap',
             'golden age hip hop',
             'underground hip hop',
             'harlem hip hop',
             'japanese old school hip hop',
             'rap',
             'bronx drill',
             'emo',
             'cali rap',
             'italian hip hop',
             'norwegian hip hop',
             'drill'],
 'house': ['hip house', 'chicago house'],
 'indie': ['modern indie folk',
           'orlando indie',
           'indie surf',
           'indietronica',
           'brisbane indie',
           'brooklyn indie',
           'indie soul',
           'indie folk',
           'indie r&b',
           'aussietronica',
           'middle earth',
           'vegas indie',
           'cologne indie',
           'australian indie',
           'indie rock',
           'afrobeats',
           'leeds indie',
           'polish indie',
           'alabama indie',
           'oxford indie',
           'norwegian singer-songwriter',
           'indie pop',
           'scottish singer-songwriter',
           'bedroom pop',
           'indie anthem-folk',
           'indie punk',
           'klubowe'],
 'jazz': ['smooth jazz',
          'nouvelle chanson francaise',
          'sung poetry',
          'jazz',
          'vocal jazz',
          'soundtrack',
          'calypso',
          'chanson',
          'soul jazz',
          'chanson paillarde',
          'jazz blues',
          'polish blues',
          'swing',
          'freestyle'],
 'latin': ['latin pop',
           'salsa',
           'bachata',
           'reggaeton',
           'bossa nova',
           'tropical'],
 'metal': ['power metal',
           'doom metal',
           'alternative metal',
           'metalcore',
           'groove metal',
           'black metal',
           'thrash metal',
           'nu metal',
           'funk metal',
           'death metal'],
 'pop': ['psychedelic pop',
         'scandipop',
         'romanian pop',
         'barbadian pop',
         'spanish indie pop',
         'lilith',
         'pop urbaine',
         'indiecoustica',
         'nz pop',
         'classic country pop',
         'german pop rock',
         'pop argentino',
         'synthpop',
         'europop',
         'british invasion',
         'neon pop punk',
         'austropop',
         'deep pop edm',
         'indie pop rap',
         'belgian pop',
         'nigerian pop',
         'new wave pop',
         'indie electropop',
         'chill pop',
         'boy band',
         'cartoon',
         'dutch pop',
         'classic polish pop',
         'experimental pop',
         'dance pop',
         'french synthpop',
         'art pop',
         'show tunes',
         'novelty',
         'post-teen pop',
         'finnish pop',
         'dream pop',
         'argentine telepop',
         'sad lo-fi',
         'urbano espanol',
         'deep acoustic pop',
         'mellow gold',
         'russian pop',
         'sped up',
         'antiviral pop',
         'pop rap',
         'swedish idol pop',
         'bubblegum pop',
         'k-pop',
         'italian pop rock',
         'idol',
         'pop electronico',
         'gen z singer-songwriter',
         'popwave',
         'classic danish pop',
         'italian adult pop',
         'urban contemporary',
         'south african pop',
         'power pop',
         'bedroom pop',
         'italian pop',
         'chamber pop',
         'polish pop',
         'singer-songwriter pop',
         'pixie',
         'vapor pop',
         'pop r&b',
         'polish viral pop',
         'social media pop',
         'classic uk pop',
         'pop',
         'latin arena pop',
         'acoustic pop',
         'classic belgian pop',
         'teen pop',
         'etherpop',
         'uk alternative pop',
         'modern indie pop',
         'mexican pop',
         'metropopolis',
         'sophisti-pop',
         'dark pop',
         'pop edm',
         'pop punk',
         'norwegian pop',
         'viral pop',
         'neo mellow',
         'classic norwegian pop',
         'pop soul',
         'brill building pop',
         'modern alternative pop',
         'bahamian pop',
         'israeli pop',
         'irish pop',
         'pop rock',
         'a cappella',
         'electropop',
         'french indie pop',
         'hip pop',
         'swedish pop',
         'uk pop',
         'canadian pop',
         'pop virale italiano',
         'italian indie pop',
         'sunshine pop',
         'swedish electropop',
         'la pop',
         'shimmer pop',
         'colombian pop',
         'channel pop',
         'classic italian pop',
         'baroque pop',
         'danish pop',
         'spanish pop',
         'ambient pop',
         'german pop',
         'french pop',
         'pop emo',
         'pop dance',
         'jangle pop',
         'hyperpop',
         'alternative pop rock',
         'hollywood',
         'pov: indie',
         'adult standards',
         'latin viral pop',
         'australian pop',
         'operatic pop',
         'afropop',
         'indie poptimism',
         'movie tunes'],
 'r&b': ['quiet storm',
         'motown',
         'british soul',
         'contemporary r&b',
         'uk contemporary r&b',
         'rebel blues',
         'afro r&b',
         'indie r&b',
         'chill r&b',
         'comic',
         'modern blues',
         'gospel r&b',
         'neo soul',
         'soul',
         'melancholia',
         'r&b',
         'bedroom soul',
         'alternative r&b',
         'lounge'],
 'reggae': ['dub', 'roots reggae', 'reggae fusion', 'reggae', 'dancehall'],
 'rock': ['industrial rock',
          'grunge',
          'rock en espanol',
          'indie garage rock',
          'french rock',
          'hard alternative',
          'progressive rock',
          'rock',
          'blues rock',
          'electronic rock',
          'latin rock',
          'pop rock',
          'british indie rock',
          'metallic hardcore',
          'post-grunge',
          'rap rock',
          'heartland rock',
          'protopunk',
          'art punk',
          'english indie rock',
          'rock nacional brasileiro',
          'broadway',
          'britpop',
          'rock alternativo brasileiro',
          'polish alternative rock',
          'polish indie rock',
          'mexican rock',
          'glam rock',
          'irish rock',
          'american metalcore',
          'symphonic power metal',
          'modern alternative rock',
          'future rock',
          'instrumental rock',
          'punk',
          'vogue',
          'balkan beats',
          'icelandic rock',
          'modern hard rock',
          'british alternative rock',
          'australian rock',
          'indie rock',
          'indie rockism',
          'rockabilly',
          'rock-and-roll',
          'piano rock',
          'classic rock',
          'psychedelic rock',
          'garage rock',
          'christian alternative rock',
          'modern blues rock',
          'funk rock',
          'afrofuturism',
          'medieval rock',
          'hard rock',
          'alternative rock',
          'soft rock',
          'folk rock',
          'chilean rock',
          'southern rock',
          'polish rock',
          'modern folk rock',
          'celtic rock',
          'yacht rock',
          'canadian indie rock',
          'modern rock',
          'peruvian rock',
          'dreamo',
          'album rock',
          'dance rock',
          'brazilian rock',
          'rock uruguayo'],
 'singer-songwriter': ['british singer-songwriter']}



SWEAR_WORD_MAPPING = {
    "damn": "d*mn",
    "hell": "h*ll",
    "crap": "c**p",
    "shit": "sh*t",
    "fuck": "f**k",
    "bitch": "b**ch",
    "bastard": "b**tard",
    "ass": "a*s",
    "dumb": "d*mb",
    "stupid": "st***d",
    "nigga": "n**ga"
}